### ISSUE TITLE
test and upgrade for WP 6.6+

### ISSUE THREAD

**Issue by chuckreynolds** [chuckreynolds/Admin-Slug-Column#17]
Support issue brings up a good point - I need to test and push an update to make sure all is good. 

https://wordpress.org/support/topic/great-plugin-but-needs-updating-2/

**Comment by slaFFik** [comment]
The plugin works with WP 6.6.

Please push the release on .org, so the plugin will again be searchable. Right now users can't even find id because it wasn't updated for several years and WP.org team demotes in search results such plugins. Thank you!

**Comment by chuckreynolds** [comment]
New `v1.6.1` is up on repo https://wordpress.org/plugins/admin-slug-column/

**Comment by slaFFik** [comment]
Thank you, @chuckreynolds!
